### ISSUE TITLE
How to hide the date on a page? How to disable Disqus for a page?

### ISSUE THREAD

**Issue by meefen** [yihui/hugo-ivy#1]
First of all, thank you for your amazing work, Yihui! I really like hugo-ivy and decided to switch from Jekyll to Hugo.

This "issue" is more two questions as I am still clueless after looking through the code. I am trying to:

- Hide the date for an About page
- Disable Disqus for the front page

Any tips?

**Comment by yihui** [comment]
As I said in README, you are on your own if you decide to use this theme. I don't have time to document it or answer questions about it. Sorry.

If you really like it, read Section 2.5 of the blogdown book: https://bookdown.org/yihui/blogdown/ That is the best I could do for you.

**Comment by meefen** [comment]
Thanks for the link. It solved this issue.

**Comment by javob** [comment]
> Thanks for the link. It solved this issue.

How did you disable Disqus from a specific page?

**Comment by oganm** [comment]
Create your own single.html. Place the code that creates the disqus between

```
{{if .Params.disqus}}
   ...  
{{end}}
```

on the page you don't want a discus, do `disqus: false` on the yaml

**Comment by javob** [comment]
Fantastic! Thank you for the answer

**Comment by oganm** [comment]
Actually it seems like there's a [built in parameter](https://github.com/yihui/hugo-ivy/blob/3a753362515d4d19dc586df8a089eb08061c681b/exampleSite/layouts/partials/disqus.html#L1) that I missed before.

**Comment by yihui** [comment]
Spot on!

**Comment by vinayprakash808** [comment]
> Thanks for the link. It solved this issue.

Hi Can you help me in solving this issue. How can I disable date here?
