### ISSUE TITLE
hugo-ivy主题下左侧边栏的菜单显示不出来

### ISSUE THREAD

**Issue by yuanyiyy** [yihui/hugo-ivy#10]
您好，我最近用hugo-ivy主题搭建了我的个人博客，地址是 https://yiyuan.vercel.app/ 。但是不知为什么，左侧边栏的菜单显示不出来。我现在是手动输入地址的方式，比如我想查看“关于”页面的内容，就是手动输入 https://yiyuan.vercel.app/about/ 。

**Comment by yihui** [comment]
1. 下次提问请扛着源代码来，无码无真相：https://github.com/yuanyiyy/blog2
2. 这个主题的首页 README 里写着我只负责写代码，不负责文档，有啥问题我也恕不负责，建议到公共论坛上提问，如：https://d.cosx.org 如果你是新手建站，我个人不是很推荐使用这个主题。
3. 如果你是袁凡的妹妹或分身，那么我可以简略回答一下你的问题；若还搞不定，请上论坛提问，让更多人帮你。
    1. config.toml 和 config.yaml 只能保留一个，建议删掉前者。
    2. config.yaml 中需要用 YAML 语法，你这里是 TOML 语法：https://github.com/yuanyiyy/blog2/blob/8fb5f0f9cd97d7cce0dd2e23ba4f305a0b7ea00e/config.yaml#L45-L50 而且这几行设置对 hugo-ivy 主题没有用，因为这个主题不会读取这些参数。

**Comment by earfanfan** [comment]
> 3. 如果你是袁凡的妹妹或分身

yihui，你好，我是袁凡，袁依不是分身，真得是我的妹妹。袁依很多内容都还没开始填，是怎么看得出来是妹妹而不是弟弟的？

>如果你是新手建站，我个人不是很推荐使用这个主题。

事情是这样的，我原本以为[hugo官网](https://themes.gohugo.io/tags/blog/)上的博客主题都是可以直接照着这篇[建站参考文章](https://cosx.org/2018/01/build-blog-with-blogdown-hugo-netlify-github)开始弄的，忽略了这个建议"Yihui 是建议用 hugo-xmin 主题开始我们的 blogdown 之旅的"，所以就让袁依直接根据自己喜好从官网选个主题。原本她选好的主题是[CaiJimmy/hugo-theme-stack](https://github.com/CaiJimmy/hugo-theme-stack)，但是在blogdown::serve_site()这一步会超时报错，我找到了相似问题在[统计之都里的一个帖子](https://d.cosx.org/d/420873-r-blogdown-serve-site-new-site)还有[stackoverflow上的帖子](https://stackoverflow.com/questions/64601786/blogdownserve-site-times-out-and-live-preview-in-viewer-does-not-load)都还是没能帮她解决问题。后来觉得"hugo-ivy"这个主题和她原本选的那个主题很像，就改用了当前这个主题。


我在帮袁依建站的时候犯了一个很大的心态上的错误，我原本以为我水平很有限，对开源的世界一直是仰视，所以认为我踩到的坑一定是前人已经踩过的也讨论出解决方案的，我没能解决问题一定是我的原因。但是那天建站的时候用“CaiJimmy/hugo-theme-stack”这个主题，到了blogdown::serve_site()这一步就会报错，但是我用"hugo-ivy"就不会报同样的错(建站用的工具R/Rstudio/git都是在袁依电脑上下载的最新版,blogdown是从CRAN下的，hugo安装是blogdown::install_hugo()装的)。我猜"同样环境下，有的主题能成功serve_site()，有的主题却不能"可能是我踩到的新坑。


后面我会介绍袁依去统计之都问问题的，当然前提是用正确的提问姿势。

**Comment by yihui** [comment]
> 是怎么看得出来是妹妹而不是弟弟的？

因为（1）我之前从 [config.yaml](https://github.com/yuanyiyy/blog2/blob/8fb5f0f9cd97d7cce0dd2e23ba4f305a0b7ea00e/config.yaml#L33) 中看到了她的真名，而“依”听起来像是女孩子名字，让我想起我很喜欢的一首诗，其中有句[相见也依依](https://yihui.org/cn/2017/04/ames/)；（2）网站的名字叫略略，这种叠字也像女孩子风格；（3）首页上写着可爱非常。如果是弟弟，就只能是六七岁；而能建网站的，就肯定不是六七岁的可爱小朋友了，大概率是二十多岁的妹妹。也不太可能是姐姐，因为这年头如果是你姐姐的年龄，那么要建站的话起码十年前就建了（像园主那样）；还没建站的人，现在来建的概率也很小了，就算你忽悠也忽悠不动了（就算动了这个念头，八成也会投奔微信公众号）。综上，你能骗得动的只有妹妹了，哈哈。

> 我原本以为我水平很有限

是的，我这几天已经忍了三次没去管闲事告诉你怎么改这里的图片地址了：https://yuanfan.vercel.app/posts/mao-mao/ 看你自己啥时候悟出来。

![image](https://user-images.githubusercontent.com/163582/108460232-d52d0100-723d-11eb-8849-7080aafb7a2e.png)

> 后面我会介绍袁依去统计之都问问题的，当然前提是用正确的提问姿势。

就这个具体问题而言，我可以在这里帮忙解决，不用去论坛了。既然我已经用了我平常的凶神恶煞面目吓唬过她一遍，那么接下来我就送佛送到西好了。

> 但是那天建站的时候用“CaiJimmy/hugo-theme-stack”这个主题，到了blogdown::serve_site()这一步就会报错

我刚测试了一下，没有报错：

![image](https://user-images.githubusercontent.com/163582/108461006-6c468880-723f-11eb-8c41-4b2c567a7ef1.png)

若不用 RStudio 的这个项目向导的话，也可以在一个空文件夹下运行：

```r
blogdown::new_site(theme = "CaiJimmy/hugo-theme-stack")
```

如果用某个主题报错的话，那很可能是我的锅，只要错误能重复，我可以修。前面说 hugo-ivy 这个主题我不推荐使用只是因为我懒得写文档，没有文档的主题只能通过读源代码来弄明白它怎么配置怎么用，而这对新手来说挑战有点大。

**Comment by earfanfan** [comment]
> 因为（1）我之前从 [config.yaml](https://github.com/yuanyiyy/blog2/blob/8fb5f0f9cd97d7cce0dd2e23ba4f305a0b7ea00e/config.yaml#L33) 中看到了她的真名，而“依”听起来像是女孩子名字，让我想起我很喜欢的一首诗，其中有句[相见也依依](https://yihui.org/cn/2017/04/ames/)；（2）网站的名字叫略略，这种叠字也像女孩子风格；（3）首页上写着可爱非常。如果是弟弟，就只能是六七岁；而能建网站的，就肯定不是六七岁的可爱小朋友了，大概率是二十多岁的妹妹。也不太可能是姐姐，因为这年头如果是你姐姐的年龄，那么要建站的话起码十年前就建了（像园主那样）；还没建站的人，现在来建的概率也很小了，就算你忽悠也忽悠不动了（就算动了这个念头，八成也会投奔微信公众号）。综上，你能骗得动的只有妹妹了，哈哈。

全中，厉害。


> 是的，我这几天已经忍了三次没去管闲事告诉你怎么改这里的图片地址了：https://yuanfan.vercel.app/posts/mao-mao/ 看你自己啥时候悟出来。

这里你要是能忍的话也可以，虽然我看你博客内容觉得你稍微是有点强迫症的。图片显示不出来的问题我初步在网上搜了的，网上给了两种解决方案，一是改本地hosts文件，二是改我网络的DNS设置，前者我试了没用，后者我觉得不靠谱。我查到的原因也有两种，一是DNS污染，二是github把图片是存在"另一个库"的，而这所谓的“另一个库”的绝对地址我还没找到。。容我再摸索下。

> 我刚测试了一下，没有报错：

我刚才又测试了一下，还是报错，截图内容我放在https://shimo.im/docs/qd39PKXWv9kvtjwx/  。我不确定你那边能不能访问石墨文档，不过我2020年初的时候曾加入了wuhan2020组织，当时也有许多小伙伴是身在海外，大家搜集更新各种资料都是在石墨文档上面，现在海外用户应该也还能访问吧。

我是先用“yihui/hugo-lithium”这个主题成功了，后用“CaiJimmy/hugo-theme-stack”这个主题失败了。


> 如果用某个主题报错的话，那很可能是我的锅，只要错误能重复，我可以修。

现在这个“报错”不能复现但存在，也说不定是这个主题的问题。我测试有问题，而你测试没问题，我在想有没有可能是因为我在墙内而你在墙外呢？

>前面说 hugo-ivy 这个主题我不推荐使用只是因为我懒得写文档，没有文档的主题只能通过读源代码来弄明白它怎么配置怎么用，而这对新手来说挑战有点大。

哈哈，在我踩坑之后我才理解你的建议的真正含义。我吐个槽，这个建议"Yihui 是建议用 hugo-xmin 主题开始我们的 blogdown 之旅的"当年没写明白啊，我估计有无数新手像我一样当时根本没理解而直接忽略了这个建议。

**Comment by earfanfan** [comment]
yihui，你好。我再补充一下，我之前用袁依的电脑时，“CaiJimmy/hugo-theme-stack”这个主题“blogdown::serve_site()”失败报的错误确实是超时；我后来用我自己的电脑和今天用公司电脑再试，才是下面这个错
>Error in shell(cmd, mustWork = TRUE, intern = intern) : 
>  '"C:\Users\User\AppData\Roaming\Hugo\hugo.exe" -b / -D -F -d "public" --themesDir themes -t hugo-theme-stack' >execution failed with error code 1

**Comment by yihui** [comment]
@earfanfan 你叫 @yuanyiyy 合并一下这个就好了：https://github.com/yuanyiyy/blog2/pull/1 这种问题我修理起来轻车熟路，放你们手里可能就摸不着头脑只能瞎碰乱试，不过我常年要冷酷无情地拒绝帮这种忙，因为量太大了；这次是碰上我正好在休假中，路见不平拔键盘相助一把好了。

你说的其它问题我看看再说。

**Comment by yihui** [comment]
> 图片显示不出来的问题……容我再摸索下。

你跑偏得有点远。算了，用国人那句无敌的话来说，就是“来都来了”，既然来都来了，就告诉你算了。目前你用的图片地址是：https://github.com/earfanfan/yf/raw/main/content/images/maomao.png 这是个网页地址，它返回的内容是 HTML 代码，而你真正要的是图片本身的地址，要获取一个 Github 文件的原始地址，可以在这个 Download 按钮（它有时候叫 Raw）上点右键复制它的原始地址：

![image](https://user-images.githubusercontent.com/163582/108520774-a4c28280-7290-11eb-8931-9d1e1dafbc78.png)

更合适的办法是把它移动到 `static/` 文件夹下：https://github.com/earfanfan/yf/tree/main/static 看这一节的第一段：https://bookdown.org/yihui/blogdown/static-files.html 当然还有更好的办法，我就先不说了，不然太晕了。

> 现在这个“报错”不能复现但存在，也说不定是这个主题的问题。我测试有问题，而你测试没问题，我在想有没有可能是因为我在墙内而你在墙外呢？

跟墙应该没有关系，我看了你的石墨文档，初步感觉是 Hugo 版本问题，你试试先升级 blogdown 包，再升级 Hugo：

```r
update.packages(ask = FALSE, checkBuilt = TRUE)
# 重启 R，然后
blogdown::install_hugo()
# 然后再重启 R，再跑
blogdown::serve_site()
```

> 我吐个槽，这个建议"Yihui 是建议用 hugo-xmin 主题开始我们的 blogdown 之旅的"当年没写明白啊

主题是 Hugo 的一大痛点，这一方面我仍需要发力，以前建议 hugo-xmin 但多数人都忍不了我这种无情的极简风，所以我还得开发一个不那么简约的主题（看 [hugo-prose](/yihui/hugo-prose) 是否有希望吧）。

**Comment by yuanyiyy** [comment]
您好，我是袁依，我已经按照您说的做了，问题已经解决了，谢谢您。

**Comment by yihui** [comment]
不客气。万事开头难，接下来应该就没那么曲折了。

**Comment by earfanfan** [comment]
> 跟墙应该没有关系，我看了你的石墨文档，初步感觉是 Hugo 版本问题，你试试先升级 blogdown 包，再升级 Hugo：
> 
> ```r
> update.packages(ask = FALSE, checkBuilt = TRUE)
> # 重启 R，然后
> blogdown::install_hugo()
> # 然后再重启 R，再跑
> blogdown::serve_site()
> ```

我照做了，但还是诡异地报错了。我瞅了一眼，我个人电脑原来的hugo是0.79，今天升级后是0.81，前几天用袁依电脑时是0.80。
事情是这样的，我先下载了“CaiJimmy/hugo-theme-stack”这个主题，然后blogdown::serve_site()报错。
![test](https://raw.githubusercontent.com/earfanfan/yf/main/static/images/test.png)
然后我又在一个新的文件夹下下载了"yihui/hugo-lithium"这个主题，然后blogdown::serve_site()虽然报错，但viewer窗格里还是出来内容了。
![test1](https://raw.githubusercontent.com/earfanfan/yf/main/static/images/test1.png)
接着我又在一个新文件夹下又下载了一次“CaiJimmy/hugo-theme-stack”这个主题，然后blogdown::serve_site()报错，但这次报的是超时那个错。
![test2](https://raw.githubusercontent.com/earfanfan/yf/main/static/images/test2.png)

这个问题先放着吧，容我去统计之都上提个新问题，看有没有小伙伴能复现我碰到的情况，说不准真是墙的原因。

**Comment by yihui** [comment]
好的，转移阵地到 https://d.cosx.org/d/422065
