### ISSUE TITLE
关于博文链接在首页的显示问题

### ISSUE THREAD

**Issue by 4fee8fea** [yihui/hugo-ivy#11]
hugo-ivy主题的首页中有下述一句话：

All pages not under the root directory of the website are listed below. You can also visit the list page of a single section, e.g., [posts](/post/), or [notes](/note/).

请问如何不显示首页的博文，而是在 /分类 或 /标签 中查阅博文呢？

**Comment by yihui** [comment]
用 `.IsHome` 变量控制：https://github.com/yihui/hugo-ivy/blob/master/layouts/_default/list.html 时间精力所限，只能帮你到这儿了。

**Comment by 4fee8fea** [comment]
谢谢！

https://bookdown.org/yihui/blogdown/templates.html#a-minimal-example

blogdown文档中记载了`.IsHome`的用法，或许查阅blogdown文档是我可以继续做下去的

**Comment by invisiblecloak-slw** [comment]
![image](https://user-images.githubusercontent.com/53552367/115878551-3dd16d80-a47b-11eb-8f24-976d758dbdf8.png)

关于导航栏有一处问题请教：

YAML文件内容如图所示。

在首页可以点击Books标签，会改变导航栏。但在更改后的导航栏中点击Computer Science将无法相应地改变导航栏，请问这是什么原因所致的呢？

谢谢！

**Comment by 4fee8fea** [comment]
![image](https://user-images.githubusercontent.com/53552367/115900341-69138700-a492-11eb-885f-695db6fd8f3b.png)
![image](https://user-images.githubusercontent.com/53552367/115900378-7a5c9380-a492-11eb-9c1e-8282d081e7ba.png)

yihui大大，我观察到如下现象：

如图，menu中指定的`url: "/en/about/"`实则指向的是`content`文件夹中的`en-about.md`文件

请问如何指向某文件夹下的子文件夹呢？
（即：content文件夹下有名为subdir的子文件夹，如何在url中以形如"subdir"的方式指定呢）

---
另外我发现当指定某文件夹，意在显示其中的全部内容而不指定_index.md时，title位置会以`s`结尾...

**Comment by yihui** [comment]
> menu中指定的`url: "/en/about/"`实则指向的是`content`文件夹中的`en-about.md`文件

因为我自定义链接了：https://github.com/yihui/yihui.org/blob/master/content/en-about.md?plain=1#L3

> 请问如何指向某文件夹下的子文件夹呢？

我不太明白这个问题。子文件夹的链接是什么，这里就填什么。

若有后续问题，我建议你去论坛提问，如 https://d.cosx.org 或 Hugo 论坛 <https://discourse.gohugo.io>。我个人实在精力有限，无法当私人顾问。请谅解。

**Comment by chuxinyuan** [comment]
修改 `themes/hugo-ivy/layouts/_default/` 路径下的 list.html 文件，代码如下：

```html
{{ partial "header.html" . }}

{{ .Content }}

{{ if not .IsHome }}
<ul>
  {{ range (where .Pages "Section" "!=" "") }}
  <li>
    <span class="date">{{ .Date.Format "2006/01/02" }}</span>
    <a href="{{ .RelPermalink }}">{{ .Title }}</a>
  </li>
  {{ end }}
</ul>
{{ end }}

{{ partial "footer.html" . }}
```
