### ISSUE TITLE
为什么使用主题后，博客的字体是非衬线字体？

### ISSUE THREAD

**Issue by meows6** [yihui/hugo-ivy#13]
我看了博主的博客，是显示的衬线字体，而我的博客用了这个主题后，字体却是非衬线字体，请问需要怎么设置成衬线字体？
这是我的博客: https://meows.moe

**Comment by yihui** [comment]
https://github.com/yihui/hugo-ivy/blob/ee82772c9140ceb320f1a2faef7ad14a5dd5299e/static/css/fonts.css#L2

**Comment by meows6** [comment]
> https://github.com/yihui/hugo-ivy/blob/ee82772c9140ceb320f1a2faef7ad14a5dd5299e/static/css/fonts.css#L2

谢谢
