### ISSUE TITLE
请问能给首页文章列表添加分页吗？

### ISSUE THREAD

**Issue by MaoVlog** [yihui/hugo-ivy#15]
希望大佬能给主题更新下。如何给首页文章列表添加分页，还又就是能给主题添加一个返回顶部按钮，就跟 [https://imhan.cn](https://imhan.cn) 一样就完美了~谢谢~

**Comment by yihui** [comment]
技术上不难，但我没有兴趣（<https://yihui.org/cn/2018/08/pagination/>）也没有时间，想分页的话可以自行看文档去实现：https://gohugo.io/templates/pagination/

顶部按钮只对移动设备有点用，桌面用户可以按 Home 键回到页面顶部。而不幸我也对支持移动设备的兴趣也不是很强烈，一般不在移动设备上读网页。若你想添加这样一个按钮，最简单的办法便是在底栏中添加一个链接 `[回到顶部](#)`：https://github.com/yihui/hugo-ivy/blob/c431a8330f2fc15b291e5a8ba86d628a53663ba5/exampleSite/config.yaml#L34
