### ISSUE TITLE
netlify不显示新增文章

### ISSUE THREAD

**Issue by swcyo** [yihui/hugo-ivy#17]
yihui大神好，最近换了ivy主题，在rstudio中新增post后server都可以看到，但是用netlify部署却不显示新增的post，只显示我之前的post是怎么回事？

https://github.com/swcyo/blog2023

**Comment by yihui** [comment]
1. 检查你的 Netlify 后台日志。
2. 你给的库我打不开。

**Comment by swcyo** [comment]
> 1. 检查你的 Netlify 后台日志。
> 2. 你给的库我打不开。

不好意思没有公开我的库（已公开），不知道是不是点击了merge branch 'main'，还是延迟部署，昨天新增的post今天可以deploy了。
不过新修改的页面设置可以显示，新push上去的post还是没有显示。

**Comment by yihui** [comment]
https://github.com/swcyo/blog2023/blob/ca9f4d09f0dde5282f9e358aee3ad08dd344e7fd/netlify.toml#L2

https://d.cosx.org/d/422234
