### ISSUE TITLE
如果首页的文章数量比较多了，如何设置首页显示数量？

### ISSUE THREAD

**Issue by tanboyu** [yihui/hugo-ivy#2]
如题，如果首页的文章数量比较多了，如何设置首页显示数量？我搜索了以下，方案是在config.toml 中设置
pagination。
谢老大能帮忙弄个分页面的方案吗？

**Comment by yihui** [comment]
1. 如 README 所说，我没有时间为这个主题写文档或帮你，你要做任何修改都要自己动手：https://github.com/yihui/hugo-ivy#readme
2. 我个人并不喜欢分页：https://yihui.name/cn/2018/08/pagination/
3. 如果你真有兴趣或有像我一样对网页有很强的控制欲，你应该读一下我的另一个极简模板的详细文档：https://bookdown.org/yihui/blogdown/templates.html 这里面已经包含了多数常见功能的实现办法，包括你要的分页。这是在我的时间范围内能做的所有事情，超出这个范围的东西，你都需要自己动手丰衣足食。
