### ISSUE TITLE
Different styles on different systems (win vs mac)

### ISSUE THREAD

**Issue by jstriaukas** [yihui/hugo-ivy#7]
It is more of a question than an issue. I am building a website to showcase my research (thus have little to none HTML/CSS experience) and I am using Hugo-ivy template (which looks great btw). I noticed that the font shift changes from mac to win, e.g. when I open https://ivy.yihui.org/ on windows I get such font; 
![win_hugo_ivy](https://user-images.githubusercontent.com/20987424/84774478-2ebd9b80-afde-11ea-997b-af0397dc4a83.PNG)
while on the mac I get the same as in this screenshot: https://github.com/yihui/hugo-ivy/blob/master/images/screenshot.png.

Is there a way to homogenize across systems (make them look as on mac)? Thanks for any help!

**Comment by yihui** [comment]
1. The fonts are defined in https://github.com/yihui/hugo-ivy/blob/master/static/css/fonts.css
1. If you want the font style to be consistent across different operating systems, you need to use fonts that are available on all platforms, e.g., https://www.w3schools.com/cssref/css_websafe_fonts.asp
